### PR TITLE
fix-issue-289: Add shortcut for adding below item

### PR DESCRIPTION
**Pull request by zzacharo**
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

### CODE REVIEW

**Comment by zzacharo** [comment]
@harunurhan I updated the interface

**Comment by jmartinm** [comment]
`mod+shift+b` does not work on Mac. The shortcut is already taken.

**Comment by zzacharo** [comment]
@jmartinm mac again :P Which should I choose?

**Comment by jmartinm** [comment]
https://support.google.com/chrome/answer/157179?hl=en

`mod+shift+c` seems to be free :P

**Comment by zzacharo** [comment]
I think there is a problem with that because I used it on copy from root and we changed it!

**Comment by jmartinm** [comment]
> I think there is a problem with that because I used it on copy from root and we changed it!

Oh, I will try locally and let you know

**Comment by jmartinm** [comment]
Nevermind. Actually `mod+shift+b` is working fine (I just had not added your commit from this PR :P). The shortcut seems to take precedence over the Chrome one, so it works.

**Pull request merged**
