### PR TITLE
issue-235: Ignore totally empty string value

### PR DESCRIPTION
**Pull request by zzacharo**
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

### CODE REVIEW

**Comment by harunurhan** [comment]
I think instead of ignoring empty, we should delete the key from `table-list-item` so this #235 is a bit bigger issue than we think.

**Comment by zzacharo** [comment]
@harunurhan if we delete `table-list-item` the whole field will be disappeared right?

**Comment by harunurhan** [comment]
@zzacharo you need to delete a key from an item of a table-list just from the record that is being emitted out. Display should be like an empty string. For I don't have a clear idea to do it but perhaps putting logic into `JsonStoreService.setIn` might be OK.

**Comment by zzacharo** [comment]
@harunurhan What is needed for this to be closed?

**Comment by harunurhan** [comment]
the same fix is in #318

**Pull request closed without merging**
