### PR TITLE
support item templates for autocomplete and refactor ref-field

### PR DESCRIPTION
**Pull request by harunurhan**
so this how it looks you can have a look (still WIP though), this is the cleanest way that I can think of, we can also use this this `templates` input for `$ref` fields in order to avoid dynamic definition and component loading.

UPDATE:

I also refactored the `ref-field` to use `<template>`, see second commit.

TODO: 
 
- [x] clean up example before the merging.

### CODE REVIEW

**Comment by jmartinm** [comment]
Looks good to me.

**Comment by harunurhan** [comment]
@jmartinm I will update it and let you know when it's ready to merge

**Comment by zzacharo** [comment]
LGTM!

**Comment by harunurhan** [comment]
@jmartinm cleaned up config and example app, ready to merge.

**Pull request merged**
