### PR TITLE
schema-format: Make schema format validation configurable

### PR DESCRIPTION
**Pull request by zzacharo**
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

### CODE REVIEW

**Comment by zzacharo** [comment]
@jmartinm Can you review this?

**Comment by jmartinm** [comment]
> @jmartinm Can you review this?

Looking now

**Comment by jmartinm** [comment]
In the example app, I can still see an error:

screen shot 2017-07-05 at 5 10 54 pm

**Comment by jmartinm** [comment]
Pending task is to create the config in the record-editor

**Comment by zzacharo** [comment]
@jmartinm For the `legacy_creation_date` there is an error in the schema I think. It will be fixed because is defined as date-time but gets date values.

**Pull request merged**
